// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk0k9TW0tlgVAdJiufR5VWqs1t_mLo0Hs',
    appId: '1:406870337024:web:2781e057c6a8dd37b2dae5',
    messagingSenderId: '406870337024',
    projectId: 'busticketbooking-43c0c',
    authDomain: 'busticketbooking-43c0c.firebaseapp.com',
    storageBucket: 'busticketbooking-43c0c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBHTylKShfs9NtpVSgfaydJsLHB4XOfhE',
    appId: '1:406870337024:android:dc7048516b40b7e7b2dae5',
    messagingSenderId: '406870337024',
    projectId: 'busticketbooking-43c0c',
    storageBucket: 'busticketbooking-43c0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDN92co_pl-4g0hVQJELoVEtcGYd8L6cc',
    appId: '1:406870337024:ios:2fc0016602debec1b2dae5',
    messagingSenderId: '406870337024',
    projectId: 'busticketbooking-43c0c',
    storageBucket: 'busticketbooking-43c0c.appspot.com',
    iosBundleId: 'com.example.busticketbooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDN92co_pl-4g0hVQJELoVEtcGYd8L6cc',
    appId: '1:406870337024:ios:4bcb38fac135379fb2dae5',
    messagingSenderId: '406870337024',
    projectId: 'busticketbooking-43c0c',
    storageBucket: 'busticketbooking-43c0c.appspot.com',
    iosBundleId: 'com.example.busticketbooking.RunnerTests',
  );
}
